# Generated by Django 3.2.7 on 2021-10-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0002_davomat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davomats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Davomat',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
