# Generated by Django 3.2.7 on 2021-10-05 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0003_auto_20211004_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='davomats',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='davomats',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
