# Generated by Django 3.2.7 on 2021-10-05 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0004_auto_20211005_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
