# Generated by Django 3.2.7 on 2021-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0005_auto_20211005_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
