# Generated by Django 3.2.7 on 2021-10-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0009_auto_20211005_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('group_choose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Davomat.group_student')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
