# Generated by Django 3.2.7 on 2021-10-05 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0011_auto_20211005_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='davomat',
            name='group_student',
        ),
    ]
