# Generated by Django 3.2.7 on 2021-10-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Davomat', '0013_auto_20211005_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Davomat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('group', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Davomats',
        ),
    ]
